### PR TITLE
Make fields validation to be run on submit

### LINKED ISSUE #25: Root Disk Size and Data Disk Size
This parameter does not have restriction and if user enters values outside of the allowed values, the cluster creation fails. This would be also good to restrict according to the platform:

"The system disk size, in GB. The value ranges from 40 to 1024."

"The data disk size, in GB. The value ranges from 100 to 32768."

### PR DESCRIPTION
**Pull request by outcatcher**
Fix #25 (one more time)

### CODE REVIEW

**Comment by outcatcher** [comment]
[component.js](https://csm-assets.obs.eu-de.otc.t-systems.com/cluster-ui-test/component.js)

**Review by lego963 — DISMISSED** [review]

File: component/component.js [hunk 1]
```diff
@@ -519,8 +517,45 @@ export default Ember.Component.extend(ClusterDriver, {
...
+      if (curr < min || curr > max) {
+        errors.push(`Cluster bandwidth is out of range ${min}-${max} (Mb)`)
+      }
+    }
+    if (step >= Steps.node) {
+      const max = get(this, 'maxNodes')
+      const min = get(this, 'minNodes')
+      const curr = get(this, 'config.nodeCount')
+      if (curr < min || curr > max) {
+        errors.push(`Node count should is out of range ${min}-${max} for selected cluster flavor`)
```
Comment (kucerakk) [inline component/component.js]: please remove 'should'

**Review by lego963 — DISMISSED** [review]

**Review by lego963 — APPROVED** [review]
